name: alchemist
description: A support package that aims to make golden testing in Flutter
  easier and more streamlined.
version: 0.10.0
homepage: https://github.com/Betterment/alchemist
repository: https://github.com/Betterment/alchemist

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.3 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: any

dev_dependencies:
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  path: any
  test: any
  version: ^3.0.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  # Used for readable platform golden tests.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
